program IWDataStat;

uses
  Forms,
  IWStart,
  UTF8ContentParser,
  UnitfrmUserLogin in 'UnitfrmUserLogin.pas' {IWfrmUserLogin: TIWAppForm},
  ServerController in 'ServerController.pas' {IWServerController: TIWServerControllerBase},
  UserSessionUnit in 'UserSessionUnit.pas' {IWUserSession: TIWUserSessionBase},
  GSProto in 'GSProto.pas',
  GSManageServer in 'GSManageServer.pas',
  EDcode in 'EDcode.pas',
  ConfigINI in 'ConfigINI.pas',
  ServerINI in 'ServerINI.pas',
  SQLFileDecrypt in '..\common\SQLFileDecrypt.pas',
  UnitfrmBasic in 'UnitfrmBasic.pas' {IWFormBasic: TIWAppForm},
  UnitIWfrmMain in 'UnitIWfrmMain.pas' {IWfrmMain: TIWAppForm},
  UnitfrmOnlineCount in 'UnitfrmOnlineCount.pas' {IWfrmOnlineCount: TIWAppForm},
  UnitfrmRole in 'UnitfrmRole.pas' {IWfrmRole: TIWAppForm},
  UnitfrmRoleLevel in 'UnitfrmRoleLevel.pas' {IWfrmRoleLevel: TIWAppForm},
  UnitfrmPayRoleLevel in 'UnitfrmPayRoleLevel.pas' {IWfrmPayRoleLevel: TIWAppForm},
  UnitfrmLevelRole in 'UnitfrmLevelRole.pas' {IWfrmLevelRole: TIWAppForm},
  UnitfrmLogin in 'UnitfrmLogin.pas' {IWfrmLogin: TIWAppForm},
  UnitIWfrmUserConsume in 'UnitIWfrmUserConsume.pas' {IWfrmUserConsume: TIWAppForm},
  UnitfrmPayUser in 'UnitfrmPayUser.pas' {IWfrmPayUser: TIWAppForm},
  UnitfrmPayAllUser in 'UnitfrmPayAllUser.pas' {IWfrmPayAllUser: TIWAppForm},
  UnitIWfrmPay in 'UnitIWfrmPay.pas' {IWfrmPay: TIWAppForm},
  UnitIWfrmConsume in 'UnitIWfrmConsume.pas' {IWfrmConsume: TIWAppForm},
  UnitIWfrmUserConsumeOrder in 'UnitIWfrmUserConsumeOrder.pas' {IWfrmUserConsumeOrder: TIWAppForm},
  UnitIWfrmPayOrder in 'UnitIWfrmPayOrder.pas' {IWfrmPayOrder: TIWAppForm},
  UnitfrmWebGrid in 'UnitfrmWebGrid.pas' {IWfrmWebGrid: TIWAppForm},
  UnitfrmLevelRank in 'UnitfrmLevelRank.pas' {IWfrmLevelRank: TIWAppForm},
  UnitfrmMoneyRank in 'UnitfrmMoneyRank.pas' {IWfrmMoneyRank: TIWAppForm},
  UnitfrmGoldRank in 'UnitfrmGoldRank.pas' {IWfrmGoldRank: TIWAppForm},
  UnitIWfrmHumLog in 'UnitIWfrmHumLog.pas' {IWfrmHumLog: TIWAppForm},
  UnitfrmNoticeGS in 'UnitfrmNoticeGS.pas' {IWfrmNoticeGS: TIWAppForm},
  UnitfrmLoginLog in 'UnitfrmLoginLog.pas' {IWfrmLoginLog: TIWAppForm},
  UnitfrmItemTrace in 'UnitfrmItemTrace.pas' {IWfrmItemTrace: TIWAppForm},
  UnitfrmItems in 'UnitfrmItems.pas' {IWfrmItems: TIWAppForm},
  UnitfrmAccountLoss in 'UnitfrmAccountLoss.pas' {IWfrmAccountLoss: TIWAppForm},
  UnitfrmRoleConsume in 'UnitfrmRoleConsume.pas' {IWfrmRoleConsume: TIWAppForm},
  UnitfrmRoleInfo in 'UnitfrmRoleInfo.pas' {IWfrmRoleInfo: TIWAppForm},
  UnitfrmActivityItem in 'UnitfrmActivityItem.pas' {IWfrmActivityItem: TIWAppForm},
  UnitfrmReloadNPC in 'UnitfrmReloadNPC.pas' {IWfrmReloadNPC: TIWAppForm},
  UnitfrmRoleGS in 'UnitfrmRoleGS.pas' {IWfrmRoleGS: TIWAppForm},
  UnitfrmFunctionGS in 'UnitfrmFunctionGS.pas' {IWfrmFunctionGS: TIWAppForm},
  UnitfrmDelayUphole in 'UnitfrmDelayUphole.pas' {IWfrmDelayUphole: TIWAppForm},
  UnitfrmExpRateGS in 'UnitfrmExpRateGS.pas' {IWfrmExpRateGS: TIWAppForm},
  UnitfrmShopGS in 'UnitfrmShopGS.pas' {IWfrmShopGS: TIWAppForm},
  UnitfrmDataEngine in 'UnitfrmDataEngine.pas' {IWfrmDataEngine: TIWAppForm},
  UnitfrmActivityItemGS in 'UnitfrmActivityItemGS.pas' {IWfrmActivityItemGS: TIWAppForm},
  UnitfrmBindGoldGS in 'UnitfrmBindGoldGS.pas' {IWfrmBindGoldGS: TIWAppForm},
  UnitfrmAccountType in 'UnitfrmAccountType.pas' {IWfrmAccountType: TIWAppForm},
  UnitfrmRoleStayTime in 'UnitfrmRoleStayTime.pas' {IWfrmRoleStayTime: TIWAppForm},
  UnitfrmCreateAccount in 'UnitfrmCreateAccount.pas' {IWfrmCreateAccount: TIWAppForm},
  UnitfrmShop in 'UnitfrmShop.pas' {IWfrmShop: TIWAppForm},
  UnitfrmShopType in 'UnitfrmShopType.pas' {IWfrmShopType: TIWAppForm},
  UnitfrmCurOnline in 'UnitfrmCurOnline.pas' {IWfrmCurOnline: TIWAppForm},
  UnitfrmGlobalOnline in 'UnitfrmGlobalOnline.pas' {IWfrmGlobalOnline: TIWAppForm},
  UnitfrmGlobalPay in 'UnitfrmGlobalPay.pas' {IWfrmGlobalPay: TIWAppForm},
  UnitfrmUserCount in 'UnitfrmUserCount.pas' {IWfrmUserCount: TIWAppForm},
  UnitfrmExtractGold in 'UnitfrmExtractGold.pas' {IWfrmExtractGold: TIWAppForm},
  UnitfrmPayDetail in 'UnitfrmPayDetail.pas' {IWfrmPayDetail: TIWAppForm},
  UnitfrmAcross in 'UnitfrmAcross.pas' {IWfrmAcross: TIWAppForm},
  UnitfrmSysExceptLog in 'UnitfrmSysExceptLog.pas' {IWfrmSysExceptLog: TIWAppForm},
  UnitfrmViewState in 'UnitfrmViewState.pas' {IWfrmViewState: TIWAppForm},
  UnitSetUserPop in 'UnitSetUserPop.pas' {IWfrmSetUserPop: TIWAppForm},
  UnitfrmBasicConfig in 'UnitfrmBasicConfig.pas' {IWfrmBasicConfig: TIWAppForm},
  UnitfrmAcrossRank in 'UnitfrmAcrossRank.pas' {IWfrmAcrossRank: TIWAppForm},
  UnitfrmAvgOnline in 'UnitfrmAvgOnline.pas' {IWfrmAvgOnline: TIWAppForm},
  UnitfrmGlobalAccount in 'UnitfrmGlobalAccount.pas' {IWfrmGlobalAccount: TIWAppForm},
  UnitfrmAccountRate in 'UnitfrmAccountRate.pas' {IWfrmAccountRate: TIWAppForm},
  UnitfrmBonusDetail in 'UnitfrmBonusDetail.pas' {IWfrmBonusDetail: TIWAppForm},
  UnitfrmBonus in 'UnitfrmBonus.pas' {IWfrmBonus: TIWAppForm},
  UnitfrmConsumeYXB in 'UnitfrmConsumeYXB.pas' {IWfrmConsumeYXB: TIWAppForm},
  UnitfrmBonusGS in 'UnitfrmBonusGS.pas' {IWfrmBonusGS: TIWAppForm},
  UnitfrmSex in 'UnitfrmSex.pas' {IWfrmSex: TIWAppForm},
  UnitfrmDataExport in 'UnitfrmDataExport.pas' {IWfrmDataExport: TIWAppForm},
  UnitfrmLoginStatus in 'UnitfrmLoginStatus.pas' {IWfrmLoginStatus: TIWAppForm},
  UnitfrmRoleActivityItemGS in 'UnitfrmRoleActivityItemGS.pas' {IWfrmRoleActivityItemGS: TIWAppForm},
  UnitfrmOperateLog in 'UnitfrmOperateLog.pas' {IWfrmOperateLog: TIWAppForm},
  UnitfrmDayLoss in 'UnitfrmDayLoss.pas' {IWfrmDayLoss: TIWAppForm},
  UnitfrmOnlineRegister in 'UnitfrmOnlineRegister.pas' {IWfrmOnlineRegister: TIWAppForm},
  UnitfrmCountry in 'UnitfrmCountry.pas' {IWfrmCountry: TIWAppForm},
  UnitfrmBindConsume in 'UnitfrmBindConsume.pas' {IWfrmBindConsume: TIWAppForm},
  UnitfrmZYRank in 'UnitfrmZYRank.pas' {IWfrmZYRank: TIWAppForm},
  UnitfrmBindGoldRank in 'UnitfrmBindGoldRank.pas' {IWfrmBindGold: TIWAppForm},
  UnitfrmReputeRank in 'UnitfrmReputeRank.pas' {IWfrmReputeRank: TIWAppForm},
  UnitfrmTaskLoss in 'UnitfrmTaskLoss.pas' {IWfrmTaskLoss: TIWAppForm},
  UnitfrmReputeShopOrder in 'UnitfrmReputeShopOrder.pas' {IWfrmReputeShopOrder: TIWAppForm},
  UnitfrmBugInfo in 'UnitfrmBugInfo.pas' {IWfrmBugInfo: TIWAppForm},
  UnitfrmAddBugInfo in 'UnitfrmAddBugInfo.pas' {IWfrmAddBugInfo: TIWAppForm},
  UnitfrmViewBugInfo in 'UnitfrmViewBugInfo.pas' {IWfrmViewBugInfo: TIWAppForm},
  UnitfrmOverview in 'UnitfrmOverview.pas' {IWfrmOverview: TIWAppForm},
  AES in 'AES.pas',
  md5 in 'md5.pas',
  UnitfrmZYCount in 'UnitfrmZYCount.pas' {IWfrmZYCount: TIWAppForm},
  UnitfrmSeedGold in 'UnitfrmSeedGold.pas' {IWfrmSeedGold: TIWAppForm},
  UnitfrmDmkjGold in 'UnitfrmDmkjGold.pas' {IWfrmDmkjGold: TIWAppForm},
  UnitfrmOpenModuleGS in 'UnitfrmOpenModuleGS.pas' {IWfrmOpenModuleGS: TIWAppForm},
  UnitfrmInsiderAccount in 'UnitfrmInsiderAccount.pas' {IWfrmInsiderAccount: TIWAppForm},
  UnitFlashPlayerVersion in 'UnitFlashPlayerVersion.pas' {IWfrmFlashPlayerVersion: TIWAppForm},
  UnitARPU in 'UnitARPU.pas' {IWfrmARPU: TIWAppForm},
  uDataDispose in 'uDataDispose.pas',
  UnitfrmStockItem in 'UnitfrmStockItem.pas' {IWfrmStockItem: TIWAppForm},
  UnitfrmSurplusMoney in 'UnitfrmSurplusMoney.pas' {IWfrmSurplusMoney: TIWAppForm},
  UnitfrmOnlineAndPay in 'UnitfrmOnlineAndPay.pas' {IWfrmOnlineAndPay: TIWAppForm},
  UnitfrmGameFeedback in 'UnitfrmGameFeedback.pas' {IWfrmGameFeedback: TIWAppForm},
  UnitfrmGameEngineList in 'UnitfrmGameEngineList.pas' {IWfrmGameEngineList: TIWAppForm},
  UnitfrmGMGS in 'UnitfrmGMGS.pas' {IWfrmGMGS: TIWAppForm},
  Share in 'Share.pas',
  UnitfrmTreasureHuntTotal in 'Newpas\UnitfrmTreasureHuntTotal.pas' {IWfrmTreasureHuntTotal: TIWAppForm},
  UnitfrmFinCurrencyTotal in 'Newpas\UnitfrmFinCurrencyTotal.pas' {IWfrmFinCurrencyTotal: TIWAppForm},
  UnitfrmHonourvalTotal in 'Newpas\UnitfrmHonourvalTotal.pas' {IWfrmHonourvalTotal: TIWAppForm},
  UnitfrmStallTrack in 'Newpas\UnitfrmStallTrack.pas' {IWfrmStallTrack: TIWAppForm},
  UnitfrmMonDieTotal in 'Newpas\UnitfrmMonDieTotal.pas' {IWfrmMonDieTotal: TIWAppForm},
  UnitfrmHumDieLevel in 'Newpas\UnitfrmHumDieLevel.pas' {IWfrmHumDieLevel: TIWAppForm},
  UnitfrmHumMapOnline in 'Newpas\UnitfrmHumMapOnline.pas' {IWfrmHumMapOnline: TIWAppForm},
  UnitfrmCopyTrack in 'Newpas\UnitfrmCopyTrack.pas' {IWfrmCopyTrack: TIWAppForm},
  UnitfrmHumdieMap in 'Newpas\UnitfrmHumdieMap.pas' {IWfrmHumdieMap: TIWAppForm},
  UnitfrmFirstConsume in 'Newpas\UnitfrmFirstConsume.pas' {IWfrmFirstConsume: TIWAppForm},
  UnitfrmConsumeLevel in 'Newpas\UnitfrmConsumeLevel.pas' {IWfrmConsumeLevel: TIWAppForm},
  UnitfrmFirstExtrYb in 'Newpas\UnitfrmFirstExtrYb.pas' {IWfrmFirstExtrYb: TIWAppForm},
  UnitfrmHunShiInfo in 'Newpas\UnitfrmHunShiInfo.pas' {IWfrmHunShiInfo: TIWAppForm},
  UnitfrmHumDropItems in 'Newpas\UnitfrmHumDropItems.pas' {IWfrmHumDropItems: TIWAppForm},
  UnitfrmFirstExtrYbCount in 'Newpas\UnitfrmFirstExtrYbCount.pas' {IWfrmFirstExtrYbCount: TIWAppForm},
  UnitfrmLoginModeTotal in 'Newpas\UnitfrmLoginModeTotal.pas' {IWfrmLoginModeTotal: TIWAppForm},
  UnitfrmLoginAgain in 'Newpas\UnitfrmLoginAgain.pas' {IWfrmLoginAgain: TIWAppForm},
  UnitfrmMonKillhum in 'Newpas\UnitfrmMonKillhum.pas' {IWfrmMonKillhum: TIWAppForm},
  UnitfrmMonStrength in 'Newpas\UnitfrmMonStrength.pas' {IWfrmMonStrength: TIWAppForm},
  UnitfrmIntegralTotal in 'Newpas\UnitfrmIntegralTotal.pas' {IWfrmIntegralTotal: TIWAppForm},
  UnitfrmHeroInfo in 'Newpas\UnitfrmHeroInfo.pas' {IWfrmHeroInfo: TIWAppForm},
  UnitEvaluate in 'UnitEvaluate.pas' {EvaluateFrm: TIWAppForm},
  UnitfrmRelati in 'Newpas\UnitfrmRelati.pas' {IWfrmRelati: TIWAppForm},
  UnitfrmCompenGS in 'Newpas\UnitfrmCompenGS.pas' {IWfrmCompenGS: TIWAppForm},
  UnitfrmAbuseGS in 'Newpas\UnitfrmAbuseGS.pas' {IWfrmAbuseGS: TIWAppForm},
  UnitfrmDropReteGS in 'Newpas\UnitfrmDropReteGS.pas' {IWfrmDropReteGS: TIWAppForm},
  UnitfrmS1Engine in 'Newpas\UnitfrmS1Engine.pas' {IWfrmS1Engine: TIWAppForm},
  UnitfrmGuildList in 'Newpas\UnitfrmGuildList.pas' {IWfrmGuildList: TIWAppForm},
  UnitfrmAllOnlineAndPay in 'UnitfrmAllOnlineAndPay.pas' {IWfrmAllOnlineAndPay: TIWAppForm},
  UnitfrmItemsTotal in 'Newpas\UnitfrmItemsTotal.pas' {IWfrmItemsTotal: TIWAppForm},
  UnitfrmIllegalInfo in 'Newpas\UnitfrmIllegalInfo.pas' {IWfrmIllegalInfo: TIWAppForm},
  UnitfrmGlobalUserYuanbao in 'Newpas\UnitfrmGlobalUserYuanbao.pas' {IWfrmGlobalUserYuanbao: TIWAppForm},
  UnitfrmVaseries in 'Newpas\UnitfrmVaseries.pas' {IWfrmVaseries: TIWAppForm},
  AIWRobot in 'AIWRobot.pas',
  UnitfrmIWStatList in 'Newpas\UnitfrmIWStatList.pas' {IWfrmIWStatList: TIWAppForm},
  IWLang in 'IWLang.pas',
  ZGSManageServer in 'ZGSManageServer.pas',
  ComCBPRead_TLB in '..\common\ComCBPRead_TLB.pas';

{$R *.res}

begin
  TIWStart.Execute(true);
end.
